#!/usr/bin/env bash
# Generate the slim portable prompt for tools with no Agent Skills support.
# The default core carries discovery, plan format, five load-bearing modules,
# the template, and portable scripts. Remaining domain modules stay as
# individually attachable files under skills/godplans/references/.
#
# Pass --full to generate the historical all-in-one prompt for a one-off use.
# The repository publishes the core because inlining every module charges the
# full context cost before applicability is known.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SKILL="$REPO_DIR/skills/godplans/SKILL.md"
REFS="$REPO_DIR/skills/godplans/references"
OUT="${GODPLANS_PROMPT_OUT:-$REPO_DIR/PROMPT.md}"
MODE=core

while [ "$#" -gt 0 ]; do
  case "$1" in
    --core)
      MODE=core
      ;;
    --full)
      MODE=full
      if [ -z "${GODPLANS_PROMPT_OUT:-}" ]; then
        OUT="$REPO_DIR/PROMPT.full.md"
      fi
      ;;
    --output)
      shift
      [ "$#" -gt 0 ] || {
        echo "--output needs a path" >&2
        exit 2
      }
      OUT=$1
      ;;
    -h|--help)
      echo "Usage: bash scripts/build-prompt.sh [--core|--full] [--output PATH]"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 2
      ;;
  esac
  shift
done

strip_frontmatter() {
  awk 'BEGIN{fm=0} /^---$/{fm++; next} fm!=1{print}' "$1"
}

# The file map points at references/*.md, unreachable from a chat surface;
# drop that section (from its heading to the next H2).
strip_file_map() {
  awk 'BEGIN{skip=0} /^## File map/{skip=1; next} skip && /^## /{skip=0} !skip{print}'
}

# Portable surfaces cannot resolve repository-relative paths. Rewrite only
# the paths that point at content inlined below; project paths such as
# .godplans/PLAN.mdx remain literal because the planning agent can access them.
portable_text_full() {
  sed \
    -e 's|Each domain has a reference module under `references/`\.|Each domain has an inlined reference module below.|g' \
    -e 's|`references/\([a-z-]*\)\.md`|the inlined \1 reference|g' \
    -e 's|references/\([a-z-]*\)\.md|the inlined \1 reference|g' \
    -e 's|`templates/PLAN\.template\.mdx`|the inlined PLAN template|g' \
    -e 's|templates/PLAN\.template\.mdx|the inlined PLAN template|g' \
    -e 's|`scripts/validate-plan\.sh`|the inlined validator|g' \
    -e 's|scripts/validate-plan\.sh|the inlined validator|g' \
    -e 's|`plan-format\.md`|the inlined plan-format reference|g' \
    -e 's|plan-format\.md|the inlined plan-format reference|g'
}

portable_text_core() {
  sed \
    -e 's|`references/compliance\.md`|the inlined compliance reference|g' \
    -e 's|`references/discovery\.md`|the inlined discovery reference|g' \
    -e 's|`references/product\.md`|the inlined product reference|g' \
    -e 's|`references/architecture\.md`|the inlined architecture reference|g' \
    -e 's|`references/stack\.md`|the inlined stack reference|g' \
    -e 's|`references/database\.md`|the inlined database reference|g' \
    -e 's|`references/security\.md`|the inlined security reference|g' \
    -e 's|`references/exemplar\.md`|the inlined exemplar reference|g' \
    -e 's|`references/plan-format\.md`|the inlined plan-format reference|g' \
    -e 's|`templates/PLAN\.template\.mdx`|the inlined PLAN template|g' \
    -e 's|`scripts/validate-plan\.sh`|the inlined validator|g' \
    -e 's|`scripts/plan-halflife\.sh`|the inlined plan half-life script|g' \
    -e 's|`plan-format\.md`|the inlined plan-format reference|g' \
    -e 's|plan-format\.md|the inlined plan-format reference|g'
}

portable_text() {
  if [ "$MODE" = "full" ]; then
    portable_text_full
  else
    portable_text_core
  fi
}

if [ "$MODE" = "full" ]; then
  REFERENCE_ORDER="
compliance discovery
product architecture stack database security llm ux ui seo code-quality
style-genome agent-memory repo build roadmap deploy observe launch
doc-set exemplar plan-format
"
else
  REFERENCE_ORDER="
compliance discovery
product architecture stack database security
exemplar plan-format
"
fi

{
  if [ "$MODE" = "full" ]; then
    cat <<'EOF'
# godplans (portable prompt)

You are operating under the godplans skill: a planning superskill that
produces a comprehensive, audit-aware master plan (PLAN.mdx) for a software
project before any code is written. This file is the flattened, single-file
form of the skill for surfaces without Agent Skills support. It includes the
orchestrator, compliance and discovery guidance, all 18 domain modules, the
quality exemplar, the documentation-set and plan-format contracts, the PLAN
template, and the self-contained validator in workflow order. No repository-local skill files
are required. When filesystem tools are available, write the inlined validator
byte-for-byte to `.godplans/validate-plan.sh` before validation. The canonical
source lives at https://github.com/hannsxpeter/godplans.

Generated by scripts/build-prompt.sh. Do not edit by hand.

---
EOF
  else
    cat <<'EOF'
# godplans (portable core)

You are operating under the godplans skill. This slim core includes discovery,
the plan contract, the five load-bearing modules (product, architecture, stack,
database, and security), the quality exemplar, the PLAN template, and the
portable scripts. It does not preload reversible or specialized domains.

Before each non-core domain pass, load that module from
`skills/godplans/references/` only when the applicability matrix marks it
applicable. The lazy modules are llm, ux, ui, seo, code-quality, style-genome,
agent-memory, repo, build, roadmap, deploy, observe, and launch. Do not author a
domain from memory and do not claim a complete plan if an applicable module was
not loaded.

`references/doc-set.md` is a contract rather than a domain, and the repo pass
needs it: it carries the document catalog, the lifecycle stages, and the
selection and exclusion rules behind `## Documentation set`. Load it with the
repo module. Without it, do not guess catalog ids.

Generated by scripts/build-prompt.sh. Do not edit by hand.

---
EOF
  fi
  strip_frontmatter "$SKILL" | strip_file_map | portable_text
  for ref in $REFERENCE_ORDER
  do
    printf '\n\n---\n\n# INLINED REFERENCE: references/%s.md\n\n' "$ref"
    portable_text < "$REFS/$ref.md"
  done
  printf '\n\n---\n\n# INLINED TEMPLATE: templates/PLAN.template.mdx\n\n'
  portable_text < "$REPO_DIR/skills/godplans/templates/PLAN.template.mdx"
  printf '\n\n---\n\n# INLINED VALIDATOR: scripts/validate-plan.sh\n\n```bash\n'
  cat "$REPO_DIR/skills/godplans/scripts/validate-plan.sh"
  printf '\n```\n'
  printf '\n\n---\n\n# INLINED SCRIPT: scripts/plan-halflife.sh\n\n```bash\n'
  cat "$REPO_DIR/skills/godplans/scripts/plan-halflife.sh"
  printf '\n```\n'
} > "$OUT"

lines=$(wc -l < "$OUT" | tr -d ' ')
bytes=$(wc -c < "$OUT" | tr -d ' ')
echo "Wrote $OUT ($MODE, $lines lines, $bytes bytes)"
